language: ruby
bundler_args: --without development
rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - 2.0.0
  - ruby-head
  - jruby-18mode
  - jruby-19mode
  - rbx-18mode
  - rbx-19mode
  - ree
gemfile:
  - Gemfile
matrix:
  allow_failures:
    - rvm:
      - ruby-head
      - jruby-18mode
      - jruby-19mode
      - rbx-18mode
      - rbx-19mode
      - ree
  include:
    - rvm: 1.8.7
      gemfile: gemfiles/ansi13minitest25.gemfile
    - rvm: 1.8.7
      gemfile: gemfiles/ansi13minitest3.gemfile
    - rvm: 1.9.3
      gemfile: gemfiles/ansi13minitest25.gemfile
    - rvm: 1.9.3
      gemfile: gemfiles/ansi13minitest3.gemfile
